name: Auto Join Swiss for Token T

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # runs every hour, at minute 0

jobs:
  auto_join:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: pip install requests

      - name: Run auto join loop
        env:
          L_TOKEN: ${{ secrets.T }}
          T_TOKEN: ${{ secrets.U }}
        run: python auto_join.py
